baseURL = "https://example.com"
languageCode = "en-us"
title = "AN LAB"
theme = "vanilla-bootstrap-hugo-theme"
googleAnalytics = "UA-123456789-1"

# Uncomment below to enable syntax highlighting
# pygmentsCodefences = true
# pygmentsCodefencesGuessSyntax = true
# See https://xyproto.github.io/splash/docs/all.html for more styles
# pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.nav]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "People"
    pre = "smile"
    url = "/people/"
    weight = 2
  [[menu.nav]]
    name = "Pubs"
    pre = "book-open"
    url = "/pubs/"
    weight = 3
  [[menu.nav]]
    name = "Blog"
    pre = "file-text"
    url = "/post/"
    weight = 4
  [[menu.nav]]
    name = "Coord"
    pre = "map-pin"
    url = "/coord/"
    weight = 5  
  [[menu.nav]]
    name = "Galaxy"
    pre = "arrow-up"
    url = "http://galaxyproject.org"
    weight = 6
  

[params]
  includeBootstrapJs = true
  showActiveNav = true
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = "Whuh"
  footerText = "AN LAB | CC-BY"
  hideFooter = false